import os
import pandas as pd
from Bio import SeqIO
from Bio.SeqRecord import SeqRecord
from Bio.Seq import Seq
pd.set_option("expand_frame_repr", False)

"""
Performs in silico digestion of Lys-C peptides using Asp-N protease specificity rules.

Asp-N Cleavage Specificity:
- Cleaves peptide bonds N-terminal to aspartic acid (D) and glutamic acid (E)
- i.e., cuts BEFORE D/E residues

Input:
- Example FASTA file: lys_c_digested_peptides.fasta (generated by running lys_c_in_silico_digestion.py)
"""


def asp_n(proseq):
    """
    Parameters:
    -----------
    proseq (str): The peptide sequence to digest
    """
    peptides = []
    cut_sites = [0]
    for i in range(0, len(proseq) - 1):
        if proseq[i] == 'E':
            cut_sites.append(i)
        elif proseq[i] == 'D':
            cut_sites.append(i)

    if cut_sites[-1] != len(proseq):
        cut_sites.append(len(proseq))
    
    # Determine maximum missed cleavages based on number of cut sites
    num_cuts = len(cut_sites)
    if num_cuts >= 10:
        max_missed = 8  # up to 8 missed cleavages
    elif num_cuts == 9:
        max_missed = 7
    elif num_cuts == 8:
        max_missed = 6
    elif num_cuts == 7:
        max_missed = 5
    elif num_cuts == 6:
        max_missed = 4
    elif num_cuts == 5:
        max_missed = 3
    elif num_cuts == 4:
        max_missed = 2
    elif num_cuts == 3:
        max_missed = 1
    else:
        # No Asp-N sites found - return entire sequence as single peptide
        peptides.append(f"{proseq}, {1}, {len(proseq)}")
        return peptides
    
    # Generate all possible peptides with up to max_missed cleavages
    for i in range(num_cuts):
        for j in range(1, min(max_missed + 2, num_cuts - i + 1)):
            if i + j < num_cuts:
                start_pos = cut_sites[i]
                end_pos = cut_sites[i + j]
                peptide_seq = proseq[start_pos:end_pos]
                peptides.append(f"{peptide_seq}, {start_pos + 1}, {end_pos}")
    
    return peptides


output = open('asp_n_digested_peptides_temp.txt', 'w')

for record in SeqIO.parse('example_input/lys_c_digested_peptides.fasta', 'fasta'):
    proseq = str(record.seq)
    peptide_list = asp_n(proseq)
    
    # Write each peptide with its position in the Lys-C peptide
    for peptide in peptide_list:
        pep_split = peptide.split(', ')
        output.write("%s\t%s\t%s\t%s\t%s\t%s\n" % (
            record.id,           # Lys-C peptide ID
            pep_split[0],        # Asp-N peptide sequence
            pep_split[1],        # Start position in Lys-C peptide
            pep_split[2],        # End position in Lys-C peptide
            len(record.seq),     # Lys-C peptide length
            record.description   # Original protein description
        ))

output.close()

# Read the digested peptides in chunks for memory efficiency
df_digest = pd.read_csv('asp_n_digested_peptides_temp.txt', sep='\t', 
                        iterator=True, chunksize=40000, header=None)

# Process each chunk and write to CSV
for chunk in df_digest:
    chunk.columns = ['id', 'peptide', 'start', 'end', 'prot len', 'description']
    
    dict_df_digest = chunk.to_dict('records')
    
    # Lists to store processed data
    Pep_seq = []
    ID = []
    ID_ = []
    Asp_N_pep_start = []
    Asp_N_pep_end = []
    Asp_N_prot_start = []
    Asp_N_prot_end = []
    description = []
    
    for index in range(len(dict_df_digest)):
        pep_seq = str(dict_df_digest[index]['peptide'])
        
        split_id = dict_df_digest[index]['id'].split('_')
        lys_c_pep_start = split_id[3]  # Start position of Lys-C peptide in protein
        
        # Calculate Asp-N peptide position in the original protein
        asp_n_prot_start = dict_df_digest[index]['start'] + int(float(lys_c_pep_start)) - 1
        asp_n_prot_end = dict_df_digest[index]['end'] + int(float(lys_c_pep_start)) - 1
        
        Pep_seq.append(pep_seq)
        ID.append(dict_df_digest[index]['id'])
        ID_.append(split_id[0])
        Asp_N_pep_start.append(dict_df_digest[index]['start'])
        Asp_N_pep_end.append(dict_df_digest[index]['end'])
        Asp_N_prot_start.append(asp_n_prot_start)
        Asp_N_prot_end.append(asp_n_prot_end)
        description.append(dict_df_digest[index]['description'])

    df = pd.DataFrame({
        'id': ID,
        'id_': ID_,
        'peptide': Pep_seq,
        'pep start': Asp_N_pep_start,
        'pep end': Asp_N_pep_end,
        'prot start': Asp_N_prot_start,
        'prot end': Asp_N_prot_end,
        'description': description
    })
    
    # Remove duplicate peptides within chunk
    # This occurs when overlapping Lys-C peptides produce identical Asp-N peptides
    df = df.drop_duplicates(subset=['prot start', 'prot end', 'id_'], 
                           keep='first', ignore_index=True)
    
    # Filter peptides by length (7-50 amino acids)
    peptide_length = df['pep end'] - df['pep start'] + 1
    df = df[(peptide_length >= 7) & (peptide_length <= 50)]
    # Append chunk to CSV file
    df.to_csv('asp_n_peptides.csv', sep=',', index=False, header=False, mode='a')

# Read the complete CSV file for final removal of duplicates
df_ = pd.read_csv('asp_n_peptides.csv', sep=',', header=None)

df_.columns = ['id', 'id_', 'peptide', 'pep start', 'pep end', 'prot start', 'prot end', 'description']

# Final removal of duplicates across all chunks
df_ = df_.drop_duplicates(subset=['prot start', 'prot end', 'id_'], 
                         keep='first', ignore_index=True)

# Drop the temporary id_ column
df_ = df_.drop(columns=['id_'])

dict_df = df_.to_dict('records')
Record_pep = []

for index in range(len(dict_df)):
    pep_seq = str(dict_df[index]['peptide'])
    
    # Create unique identifier
    acc = f"{dict_df[index]['id']}_{dict_df[index]['prot start']}_{dict_df[index]['prot end']}"
    
    descr = dict_df[index]['description']
    record = SeqRecord(Seq(pep_seq), id=acc, description=descr)
    Record_pep.append(record)

if not os.path.exists('output'):
        os.makedirs('output')  
        
# Write peptide database in FASTA format
SeqIO.write(Record_pep, "output/asp_n_digested_peptides.fasta", "fasta")
print("Writing to FASTA file ... Completed")

# Remove temporary files
os.remove("asp_n_digested_peptides_temp.txt")
os.remove("asp_n_peptides.csv")
