import pandas as pd
from Bio import SeqIO
from Bio.SeqRecord import SeqRecord
from Bio.Seq import Seq
import os

"""
Performs in silico digestion of Lys-C peptides using Glu-C endopeptidase specificity:
- Cuts peptide bonds C-terminal to aspartic acid (D) and glutamic acid (E) i.e. cuts after D/E

Input:
- Example FASTA file: lys_c_digested_peptides.fasta (generated by running lys_c_in_silico_digestion.py)
"""

def glu_c(proseq):
    """
    Parameters:
    -----------
        proseq (str): The peptide sequence to digest
    """
    peptides = []
    cut_sites = [0]  # Include N-terminus as first cut site
    
    # Identify Glu-C cleavage sites
    for i in range(len(proseq) - 1):
        if proseq[i] == 'D' and proseq[i + 1] != 'P':
            cut_sites.append(i + 1)
        elif proseq[i] == 'E' and proseq[i + 1] != 'P':
            cut_sites.append(i + 1)
    
    if cut_sites[-1] != len(proseq):
        cut_sites.append(len(proseq))
    
    n = len(cut_sites)  # Total number of cut sites including termini
    
    if n >= 10:  # up to 8 missed cleavages
        for j in range(n - 9):
            for k in range(1, 10): 
                peptides.append(f"{proseq[cut_sites[j]:cut_sites[j + k]]}, {cut_sites[j] + 1}, {cut_sites[j + k]}")
        
        for start_idx in range(-9, -1): 
            for end_idx in range(start_idx + 1, 0): 
                peptides.append(f"{proseq[cut_sites[start_idx]:cut_sites[end_idx]]}, {cut_sites[start_idx] + 1}, {cut_sites[end_idx]}")
    
    elif n == 9:  # up to 7 missed cleavages
        for j in range(n - 8):
            for k in range(1, 9):
                peptides.append(f"{proseq[cut_sites[j]:cut_sites[j + k]]}, {cut_sites[j] + 1}, {cut_sites[j + k]}")
        
        for start_idx in range(-8, -1):
            for end_idx in range(start_idx + 1, 0):
                peptides.append(f"{proseq[cut_sites[start_idx]:cut_sites[end_idx]]}, {cut_sites[start_idx] + 1}, {cut_sites[end_idx]}")
    
    elif n == 8:  # up to 6 missed cleavages
        for j in range(n - 7):
            for k in range(1, 8):
                peptides.append(f"{proseq[cut_sites[j]:cut_sites[j + k]]}, {cut_sites[j] + 1}, {cut_sites[j + k]}")
        
        for start_idx in range(-7, -1):
            for end_idx in range(start_idx + 1, 0):
                peptides.append(f"{proseq[cut_sites[start_idx]:cut_sites[end_idx]]}, {cut_sites[start_idx] + 1}, {cut_sites[end_idx]}")
    
    elif n == 7:  # up to 5 missed cleavages
        for j in range(n - 6):
            for k in range(1, 7):
                peptides.append(f"{proseq[cut_sites[j]:cut_sites[j + k]]}, {cut_sites[j] + 1}, {cut_sites[j + k]}")
        
        for start_idx in range(-6, -1):
            for end_idx in range(start_idx + 1, 0):
                peptides.append(f"{proseq[cut_sites[start_idx]:cut_sites[end_idx]]}, {cut_sites[start_idx] + 1}, {cut_sites[end_idx]}")
    
    elif n == 6:  # up to 4 missed cleavages
        for j in range(n - 5):
            for k in range(1, 6):
                peptides.append(f"{proseq[cut_sites[j]:cut_sites[j + k]]}, {cut_sites[j] + 1}, {cut_sites[j + k]}")
        
        for start_idx in range(-5, -1):
            for end_idx in range(start_idx + 1, 0):
                peptides.append(f"{proseq[cut_sites[start_idx]:cut_sites[end_idx]]}, {cut_sites[start_idx] + 1}, {cut_sites[end_idx]}")
    
    elif n == 5:  # up to 3 missed cleavages
        for j in range(n - 4):
            for k in range(1, 5):
                peptides.append(f"{proseq[cut_sites[j]:cut_sites[j + k]]}, {cut_sites[j] + 1}, {cut_sites[j + k]}")
        
        for start_idx in range(-4, -1):
            for end_idx in range(start_idx + 1, 0):
                peptides.append(f"{proseq[cut_sites[start_idx]:cut_sites[end_idx]]}, {cut_sites[start_idx] + 1}, {cut_sites[end_idx]}")
    
    elif n == 4:  # up to 2 missed cleavages
        for j in range(n - 3):
            for k in range(1, 4):
                peptides.append(f"{proseq[cut_sites[j]:cut_sites[j + k]]}, {cut_sites[j] + 1}, {cut_sites[j + k]}")
        
        for start_idx in range(-3, -1):
            for end_idx in range(start_idx + 1, 0):
                peptides.append(f"{proseq[cut_sites[start_idx]:cut_sites[end_idx]]}, {cut_sites[start_idx] + 1}, {cut_sites[end_idx]}")
    
    elif n == 3:  # (up to 1 missed cleavage)
        for j in range(n - 2):
            for k in range(1, 3): 
                peptides.append(f"{proseq[cut_sites[j]:cut_sites[j + k]]}, {cut_sites[j] + 1}, {cut_sites[j + k]}")

        peptides.append(f"{proseq[cut_sites[-2]:cut_sites[-1]]}, {cut_sites[-2] + 1}, {cut_sites[-1]}")
    else:  # No Glu-C cleavage sites found
        # Return the entire sequence as a single peptide
        peptides.append(f"{proseq}, {1}, {len(proseq)}")
    
    return peptides


output = open('glu_c_digested_peptides_temp.txt', 'w')

for record in SeqIO.parse('example_input/lys_c_digested_peptides.fasta', 'fasta'):
    proseq = str(record.seq)
    peptide_list = glu_c(proseq)  # Perform Glu-C digestion
    
    for peptide in peptide_list:
        pep_split = peptide.split(', ')
        # Format: ID, peptide_sequence, start position in lysC peptide, end position in lysC peptide, lysC_peptide_length, description
        output.write(f"{record.id}\t{pep_split[0]}\t{pep_split[1]}\t{pep_split[2]}\t"
                    f"{len(record.seq)}\t{record.description}\n")

output.close()

# Process peptides in chunks for memory efficiency
df_chunks = []  
df_digest = pd.read_csv('glu_c_digested_peptides_temp.txt', sep='\t', 
                        iterator=True, chunksize=40000, header=None)  

for chunk in df_digest:
    chunk.columns = ['id', 'peptide', 'start', 'end', 'prot len', 'description']
    
    # Extract protein positions from Lys-C peptide IDs
    chunk['id_parts'] = chunk['id'].str.split('_')
    chunk['lys_c_pep_start'] = chunk['id_parts'].str[2].astype(float).astype(int)  # Start of Lys-C peptide in protein
    chunk['id_'] = chunk['id_parts'].str[0]  # Original protein accession
    
    # Calculate positions in the original protein
    chunk['prot start'] = chunk['start'] + chunk['lys_c_pep_start'] - 1  # Glu-C start in protein coordinates
    chunk['prot end'] = chunk['end'] + chunk['lys_c_pep_start'] - 1      # Glu-C end in protein coordinates
    
    chunk = chunk[['id', 'id_', 'peptide', 'start', 'end', 
                   'prot start', 'prot end', 'description']]
    chunk.columns = ['id', 'id_', 'peptide', 'pep start', 'pep end', 
                     'prot start', 'prot end', 'description']
    
    # Remove duplicate peptides from the same protein
    # Duplicates occur when overlapping Lys-C peptides yield identical Glu-C peptides
    chunk = chunk.drop_duplicates(subset=['prot start', 'prot end', 'id_'], keep='first')
    
    peptide_length = chunk['pep end'] - chunk['pep start'] + 1
    chunk = chunk[(peptide_length >= 5) & (peptide_length <= 63)]  # Keep peptides 5-63 amino acids long
    
    df_chunks.append(chunk)

# Combine all chunks and remove duplicates
df_combined = pd.concat(df_chunks, ignore_index=True)
df_combined = df_combined.drop_duplicates(subset=['prot start', 'prot end', 'id_'], keep='first')
df_combined = df_combined.drop(columns=['id_'])  # Remove temporary protein ID column


records = []
for _, row in df_combined.iterrows():
    # Create unique peptide ID
    acc = f"{row['id']}_{row['prot start']}_{row['prot end']}"
    record = SeqRecord(Seq(row['peptide']), id=acc, description=row['description'])
    records.append(record)

if not os.path.exists('output'):
        os.makedirs('output')  
        
# Write peptide database in FASTA format
SeqIO.write(records, "output/glu_c_digested_peptides.fasta", "fasta")
print("Writing to FASTA file ... Completed")

# Remove temporary files
os.remove("glu_c_digested_peptides_temp.txt")
